[package]
name = "networks"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "^0.55.0", features = [
  "noise",
  "ping",
  "tcp",
  "tokio",
  "yamux",
  "dns",
] }

tokio = { version = "1.43.0", features = ["full"] }
