[package]
name = "transaction"
version = "0.1.0"
edition = "2024"

[dependencies]
secp256k1 = { version = "0.30.0", features = ["rand", "hashes"] }
serde = { version = "1.0.219", features = ["derive"] }
