[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
hex = "0.4.3"
rocksdb = "0.23.0"
tracing = "0.1.41"
serde ="1.0.217"
serde_json = "1.0.140"

account = {path = "../account"}